In [2]:
import numpy as np
import random 

In [3]:
# 2D array
s = (4,4)
arr2d = np.ones(s, dtype=int)
arr2d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [4]:
# Flatten
arr2d = arr2d.flatten()
print(arr2d)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [5]:
arr2d.shape

(16,)

In [6]:
s = (4,4)
arr1d = np.zeros(s, dtype=int)
arr1d

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
arr1d.shape

(4, 4)

In [8]:
# Define the initial and goal states
initial_state = np.zeros((4, 4), dtype=int)
goal_state = np.ones((4, 4), dtype=int)

# Convert the 2D array to a 1D array of length 16
initial_chromosome = initial_state.reshape(16)

def calculate_fitness(chromosome):
    # Calculate the fitness value of a chromosome as the number of ones in the array
    return np.count_nonzero(chromosome == 1)

def selection(population, fitnesses):
    # Add a small positive constant to fitness values to avoid zero probabilities
    fitnesses = np.array(fitnesses) + 1e-6
    # Calculate the selection probabilities based on fitness values
    total_fitness = sum(fitnesses)
    selection_probabilities = [fitness / total_fitness for fitness in fitnesses]
    # Normalize the selection probabilities
    selection_probabilities = [prob / sum(selection_probabilities) for prob in selection_probabilities]
    # Select two parents randomly using the selection probabilities
    parents_indices = np.random.choice(len(population), size=2, replace=False, p=selection_probabilities)
    parents = [population[i] for i in parents_indices]
    return parents



def crossover(parents):
    # Perform a single-point crossover operation on the selected parents
    crossover_point = random.randint(0, len(parents[0]))
    child1 = np.concatenate((parents[0][:crossover_point], parents[1][crossover_point:]))
    child2 = np.concatenate((parents[1][:crossover_point], parents[0][crossover_point:]))
    return [child1, child2]

def mutation(children, mutation_rate):
    # Apply the mutation operator with a low probability value to introduce new genetic material
    for i in range(len(children)):
        for j in range(len(children[i])):
            if np.random.rand() < mutation_rate:
                children[i][j] = 1 - children[i][j]
    return children

def genetic_algorithm(population, max_iterations, mutation_rate):
    # Initialize iteration counter
    iteration = 0

    # Repeat until max_iterations or solution is found
    while iteration < max_iterations:
        # Evaluate fitness of population
        fitnesses = [calculate_fitness(chromosome) for chromosome in population]

        # Check for solution
        if np.max(fitnesses) == len(initial_chromosome):
            return population[np.argmax(fitnesses)]

        # Select parents
        parents = selection(population, fitnesses)

        # Generate children through crossover
        children = crossover(parents)

        # Apply mutation to children
        children = mutation(children, mutation_rate)

        # Calculate fitness values of the new children
        children_fitness = [calculate_fitness(child) for child in children]

        # Check if any of the children is a solution
        if np.max(children_fitness) == len(initial_chromosome):
            return children[np.argmax(children_fitness)]

        # Replace the least fit members of the population with the new children
        worst_fitness_indices = np.argsort(fitnesses)[:len(children)]
        for i, child in enumerate(children):
            population[worst_fitness_indices[i]] = child

        # Increment iteration counter
        iteration += 1

    # Return best solution found
    return population[np.argmax(fitnesses)]

# Generate an initial population of chromosomes
population_size = 20
population = [initial_chromosome for i in range(population_size)]

# Set the maximum number of iterations and mutation rate
max_iterations = 1000
mutation_rate = 0.01

# Run the genetic algorithm to find a solution
solution = genetic_algorithm(population, max_iterations, mutation_rate)

solution

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])